# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Users\jssanche\Documents\Steven\Reto\Principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(611, 659)
        MainWindow.setMinimumSize(QtCore.QSize(611, 659))
        MainWindow.setMaximumSize(QtCore.QSize(611, 659))
        MainWindow.setStyleSheet("background-color :rgb(91, 91, 91);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setEnabled(True)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 591, 601))
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(5555, 5555))
        self.frame_2.setSizeIncrement(QtCore.QSize(582, 574))
        self.frame_2.setStyleSheet("\n"
"QFrame{\n"
"background-color: rgb(0,206,151);\n"
"background-color: rgb(0, 60, 88);\n"
"border:1.5px solid whiter;\n"
"border-radius:20px;\n"
"\n"
"border-top:3px solid  rgb(0,0,0);\n"
"border-left:3px solid  rgb(0,0,0)\n"
"}\n"
"QLineEdit{\n"
"background-color: rgb(103, 197, 255);\n"
"}\n"
"\n"
"QLabel{\n"
"background-color: rgb(0, 255, 255);\n"
"}\n"
"\n"
"QTableWidget{\n"
"font-size:20pt;\n"
"background-color: rgb(211, 254, 238);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"\n"
"QLineEdit{\n"
"\n"
"color:rgb(240, 255, 250);\n"
"background-color: transparent;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 17pt \"MS Shell Dlg 2\";\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.textEdit = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(70, -10, 471, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setStyleSheet("\n"
"background-color :rgb(91, 91, 91);\n"
"font: 24pt \"MS Shell Dlg 2\";\n"
"border-radius:15px;\n"
"border:2px solid whiter;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"\n"
"border-right:3px solid rgb(0,0,0);\n"
"border-bottom:3px solid rgb(0,0,0)")
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setAcceptRichText(True)
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_2.setEnabled(False)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 50, 561, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_2.sizePolicy().hasHeightForWidth())
        self.textEdit_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("QFrame{\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius:15px;\n"
"border:1px solid rgb(255, 255, 255);\n"
"border-top:3px solid  rgb(255, 255, 255);\n"
"border-left:3px solid  rgb(255, 255, 255)\n"
"}\n"
"")
        self.textEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setAcceptRichText(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        self.frame_7.setGeometry(QtCore.QRect(10, 270, 561, 321))
        self.frame_7.setStyleSheet("\n"
"QFrame{\n"
"background-color: rgb(0,206,151);\n"
"background-color: rgb(0, 60, 88);\n"
"border:1px solid rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"border-top:3px solid  rgb(255, 255, 255);\n"
"border-left:3px solid  rgb(255, 255, 255)\n"
"\n"
"}\n"
"QLineEdit{\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border-radius:12px;\n"
"border:1px solid rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QLabel{\n"
"background-color: rgb(0, 255, 255);\n"
"}\n"
"\n"
"QTableWidget{\n"
"font-size:20pt;\n"
"background-color: rgb(211, 254, 238);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"\n"
"QLineEdit{\n"
"\n"
"color:rgb(240, 255, 250);\n"
"background-color: transparent;\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton{\n"
"\n"
"border:2px solid rgb(0,0,0);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border-radius:14px;\n"
"\n"
"\n"
"background-color: rgb(193, 193, 193);\n"
"border:1px solid whiter;\n"
"border-right:6px solid rgb(80,80,80);\n"
"border-bottom:6px solid rgb(80,80,80)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(156, 156, 156);\n"
"border-right:none;\n"
"border-bottom:none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(156, 156, 156)\n"
"\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.textEdit_3 = QtWidgets.QTextEdit(self.frame_7)
        self.textEdit_3.setEnabled(False)
        self.textEdit_3.setGeometry(QtCore.QRect(370, 40, 181, 261))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_3.sizePolicy().hasHeightForWidth())
        self.textEdit_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setStyleSheet("QFrame{\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius:15px;\n"
"border:1px solid rgb(255, 255, 255);\n"
"border-top:1px solid  rgb(255, 255, 255);\n"
"border-left:1px solid  rgb(255, 255, 255)\n"
"}\n"
"")
        self.textEdit_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_3.setAcceptRichText(True)
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.frame_7)
        self.textEdit_4.setEnabled(False)
        self.textEdit_4.setGeometry(QtCore.QRect(190, 40, 171, 261))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_4.sizePolicy().hasHeightForWidth())
        self.textEdit_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_4.setFont(font)
        self.textEdit_4.setStyleSheet("QFrame{\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius:15px;\n"
"border:1px solid rgb(255, 255, 255);\n"
"border-top:1px solid  rgb(255, 255, 255);\n"
"border-left:1px solid  rgb(255, 255, 255)\n"
"}\n"
"")
        self.textEdit_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_4.setAcceptRichText(True)
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.frame_7)
        self.textEdit_5.setEnabled(False)
        self.textEdit_5.setGeometry(QtCore.QRect(10, 40, 171, 261))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_5.sizePolicy().hasHeightForWidth())
        self.textEdit_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_5.setFont(font)
        self.textEdit_5.setStyleSheet("QFrame{\n"
"border-color: rgb(0, 0, 0);\n"
"border-radius:15px;\n"
"border:1px solid rgb(255, 255, 255);\n"
"border-top:1px solid  rgb(255, 255, 255);\n"
"border-left:1px solid  rgb(255, 255, 255)\n"
"}\n"
"")
        self.textEdit_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_5.setAcceptRichText(True)
        self.textEdit_5.setObjectName("textEdit_5")
        self.label_9 = QtWidgets.QLabel(self.frame_7)
        self.label_9.setGeometry(QtCore.QRect(20, 120, 151, 161))
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: transparent;\n"
"border:0px")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("d:\\Users\\jssanche\\Documents\\Steven\\Reto\\Imagenes/lanzadora-removebg-preview.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.Boton_Lanzamiento = QtWidgets.QPushButton(self.frame_7)
        self.Boton_Lanzamiento.setEnabled(True)
        self.Boton_Lanzamiento.setGeometry(QtCore.QRect(20, 50, 151, 70))
        self.Boton_Lanzamiento.setSizeIncrement(QtCore.QSize(0, 0))
        self.Boton_Lanzamiento.setStyleSheet("")
        self.Boton_Lanzamiento.setAutoDefault(False)
        self.Boton_Lanzamiento.setDefault(False)
        self.Boton_Lanzamiento.setFlat(False)
        self.Boton_Lanzamiento.setObjectName("Boton_Lanzamiento")
        self.Boton_NTripulada = QtWidgets.QPushButton(self.frame_7)
        self.Boton_NTripulada.setEnabled(True)
        self.Boton_NTripulada.setGeometry(QtCore.QRect(200, 50, 151, 70))
        self.Boton_NTripulada.setSizeIncrement(QtCore.QSize(0, 0))
        self.Boton_NTripulada.setStyleSheet("")
        self.Boton_NTripulada.setAutoDefault(False)
        self.Boton_NTripulada.setDefault(False)
        self.Boton_NTripulada.setFlat(False)
        self.Boton_NTripulada.setObjectName("Boton_NTripulada")
        self.label_10 = QtWidgets.QLabel(self.frame_7)
        self.label_10.setGeometry(QtCore.QRect(200, 130, 151, 151))
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: transparent;\n"
"border:0px")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("d:\\Users\\jssanche\\Documents\\Steven\\Reto\\Imagenes/Notripulada-removebg-preview.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.Boton_Tripulada = QtWidgets.QPushButton(self.frame_7)
        self.Boton_Tripulada.setEnabled(True)
        self.Boton_Tripulada.setGeometry(QtCore.QRect(380, 50, 161, 70))
        self.Boton_Tripulada.setSizeIncrement(QtCore.QSize(0, 0))
        self.Boton_Tripulada.setStyleSheet("")
        self.Boton_Tripulada.setAutoDefault(False)
        self.Boton_Tripulada.setDefault(False)
        self.Boton_Tripulada.setFlat(False)
        self.Boton_Tripulada.setObjectName("Boton_Tripulada")
        self.label_11 = QtWidgets.QLabel(self.frame_7)
        self.label_11.setGeometry(QtCore.QRect(380, 130, 151, 141))
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: transparent;\n"
"border:0px")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("d:\\Users\\jssanche\\Documents\\Steven\\Reto\\Imagenes/tripulada-removebg-preview.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.textEdit_5.raise_()
        self.textEdit_3.raise_()
        self.textEdit_4.raise_()
        self.label_9.raise_()
        self.Boton_Lanzamiento.raise_()
        self.Boton_NTripulada.raise_()
        self.label_10.raise_()
        self.Boton_Tripulada.raise_()
        self.label_11.raise_()
        self.label_turno = QtWidgets.QLabel(self.frame_2)
        self.label_turno.setGeometry(QtCore.QRect(160, 250, 251, 39))
        self.label_turno.setStyleSheet("border:2px solid rgb(0, 0, 0);\n"
"border-radius:12px;\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(211, 254, 238);\n"
"background-color: rgb(190, 190, 190);")
        self.label_turno.setAlignment(QtCore.Qt.AlignCenter)
        self.label_turno.setObjectName("label_turno")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 611, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:24pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Naves Espaciales</p></body></html>"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-weight:400; color:#ffffff;\">A continuación se podrá seleccionar tres tipos de naves espaciales, La cuales se podrán consultar y agregar información a Base de Datos.</span></p></body></html>"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Boton_Lanzamiento.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.Boton_Lanzamiento.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.Boton_Lanzamiento.setText(_translate("MainWindow", "Lanzamiento"))
        self.Boton_NTripulada.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.Boton_NTripulada.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Boton Ventana</p></body></html>"))
        self.Boton_NTripulada.setText(_translate("MainWindow", "No Tripuladas"))
        self.Boton_Tripulada.setToolTip(_translate("MainWindow", "<html><head/><body><p/></body></html>"))
        self.Boton_Tripulada.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Boton Ventana</p></body></html>"))
        self.Boton_Tripulada.setText(_translate("MainWindow", "Tripuladas"))
        self.label_turno.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Paroo</p></body></html>"))
        self.label_turno.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\">Paro oep</p></body></html>"))
        self.label_turno.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Tipos de Naves</p></body></html>"))
